#!/bin/bash -ex

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

MS_REPO=$FAB_PATH/products/mediaserver
TS_REPO=$FAB_PATH/products/torrentserver

REPO=$(pwd)

[ -d "$MS_REPO" ] || fatal "$MS_REPO doesn't exist"
[ -d "$TS_REPO" ] || fatal "$TS_REPO doesn't exist"

mkdir -p $PWD/conf.d/{torrentserver,mediaserver}

cd $MS_REPO
cp conf.d/* $REPO/conf.d/torrentserver
cp -R overlay $REPO

cd $TS_REPO
cp conf.d/* $REPO/conf.d/mediaserver
cp -R overlay $REPO

cd $REPO
cp -R build-overlay/* .

