#!/bin/bash -ex

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

copy_app() {
    REPO=$FAB_PATH/products/$1
    [ -d "$REPO" ] || fatal "$REPO doesn't exist"
    cp $REPO/conf.d/downloads conf.d/$1-downloads
    cp $REPO/conf.d/main conf.d/$1-main
    cp -R $REPO/overlay .
}

copy_app torrentserver
copy_app mediaserver

cp -R build-overlay/* .

