#!/bin/sh -ex

STORAGE=/srv/storage
PASSWORD=turnkey
SRC=/usr/local/src
WEBROOT=/var/www/rutorrent
INST_DIR=/opt
MEDIA_HOME=$INST_DIR/media-server
MEDIA_USER=media

#create user for other software
mkdir -p $MEDIA_HOME
useradd --user-group --system --home $MEDIA_HOME --shell /bin/false --groups users $MEDIA_USER
chown -R $MEDIA_USER:$MEDIA_USER $MEDIA_HOME

# sabnzbd
DEFAULT=/etc/default/sabnzbdplus
sed -i "s|USER=.*|USER=\"$MEDIA_USER\"|g" $DEFAULT
sed -i "s|HOST=.*|HOST=0.0.0.0|g" $DEFAULT
sed -i "s|PORT=.*|PORT=8080|g" $DEFAULT
update-rc.d sabnzbdplus defaults

USER=$MEDIA_USER:root
RUN=/var/run
DATA=/var/lib
CONF=/etc

mkdir_chown() {
    for ARG; do
        mkdir -p $ARG
        chown $USER $ARG
    done
}

install_app() {
    # NAME & NM
    NAME=$1
    NM=$2

    DEFAULT=/etc/default/$NAME
    INIT=/etc/init.d/$NAME
    RUN_DIR=$RUN/$NAME
    DATA_DIR=$DATA/$NAME
    HOME_DIR=$INST_DIR/$NAME
    CONF_DIR=$CONF/$NAME

    mkdir_chown $RUN_DIR $DATA_DIR $HOME_DIR $CONF_DIR

    INIT_FILES="$HOME_DIR/init/ubuntu $HOME_DIR/runscripts/init.ubuntu 
        $HOME_DIR/init-scripts/init.ubuntu $HOME_DIR/initd"
    # couchpotato SickRage headphones & maraschino

    for INIT_FILE in $INIT_FILES; do
        if [ -f "$INIT_FILE" ]; then
            INIT_SCRIPT=$INIT_FILE
            if [ "$NAME" = "maraschino" ]; then
                cp $HOME_DIR/default $DEFAULT
                sed -i "/APP_PATH/ s|=.*|= $HOME_DIR|" $DEFAULT
                sed -i "/RUN_AS/ s|=.*|= $MEDIA_USER|" $DEFAULT
                sed -i "/PID_FILE/ s|=.*|= $RUN_DIR/$NAME.pid|" $DEFAULT
            else
                cat > $DEFAULT <<EOF
# OPTIONS: ${NM}_USER, ${NM}_HOME, ${NM}_DATA, ${NM}_PIDFILE, PYTHON_BIN, ${NM}_OPTS, SSD_OPTS
${NM}_USER=$MEDIA_USER
${NM}_HOME=$HOME_DIR
${NM}_DATA=$DATA_DIR
${NM}_PIDFILE=$RUN_DIR/$NAME.pid
${NM}_OPTS=" --config=$CONF_DIR/config.ini"
EOF
            fi
        fi
    done

    cp $INIT_SCRIPT $INIT
    chmod +x $INIT
   
    update-rc.d $NAME defaults

    service $NAME start && sleep 10
    service $NAME stop && sleep 10
   
}

install_app maraschino

install_app couchpotato CP
# port

install_app sickrage SR
# port

install_app headphones HP
# port 8181 

ln -s /etc/nginx/sites-available/maraschino-rtorrent /etc/nginx/sites-enabled/maraschino-rtorrent
